#!/bin/bash
#
#
# aasta muutuja kuna president valiti
aasta="2016"
president="Kesti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks "
lause=$aasta$lause_keskosa$president
#
#
echo $lause
#
#skripti lõpp
#
