#!/bin/bash
#
osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"
echo -n "Select your OS choice [1 or 2]? "
read osch
#
if [ $osch -eq 1 ] ; then
	echo "You pick up Unix (Sun OS)"
else #### nested if i.e. if within if #####
	if [ $osch -eq 2 ] ; then
		echo "You Pick up Linux (Red Hat)"
	else
		echo "What you dont like Unix/Linus OS."
	fi
fi
#
#
